# 2.LECTURA DE DATOS EFICIENCIA DEL AGUA

In [2]:
import pandas as pd

RUTA = "../data/WB_CLEAR_AQUASTAT_4554.csv"

# Lectura completa del archivo CSV
datos = pd.read_csv(RUTA)

print(f"Filas: {datos.shape[0]}")
print(f"Columnas: {datos.shape[1]}")
datos.head()

Filas: 1407
Columnas: 37

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public

In [6]:
df = pd.read_csv(
    RUTA,
    sep=",",
    encoding="utf-8",
    decimal=".",
    na_values=["", "NA", "N/A", "-", "null", "999"],
    skipinitialspace=True,
)

print(df.shape)
print(df.info())
df.head()

(1407, 37)
<class 'pandas.DataFrame'>
RangeIndex: 1407 entries, 0 to 1406
Data columns (total 37 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   STRUCTURE               1407 non-null   str
 1   STRUCTURE_ID            1407 non-null   str
 2   ACTION                  1407 non-null   str
 3   FREQ                    1407 non-null   str
 4   FREQ_LABEL              1407 non-null   str
 5   REF_AREA                1407 non-null   str
 6   REF_AREA_LABEL          1407 non-null   str
 7   INDICATOR               1407 non-null   str
 8   INDICATOR_LABEL         1407 non-null   str
 9   SEX                     1407 non-null   str
 10  SEX_LABEL               1407 non-null   str
 11  AGE                     1407 non-null   str
 12  AGE_LABEL               1407 non-null   str
 13  URBANISATION            1407 non-null   str
 14  URBANISATION_LABEL      1407 non-null   str
 15  UNIT_MEASURE            1407 non-null   str
 16  UNIT_MEASURE_LABEL      1407 non-null   str
 17  COMP_BREAKDOWN_1        1407 non-null   str
 18  COMP_BREAKDOWN_1_LABEL  1407 non-null   str
 19  COMP_BREAKDOWN_2        1407 non-null   str
 20  COMP_BREAKDOWN_2_LABEL  1407 non-null   str
 21  COMP_BREAKDOWN_3        1407 non-null   str
 22  COMP_BREAKDOWN_3_LABEL  1407 non-null   str
 23  TIME_PERIOD             1407 non-null   int64
 24  OBS_VALUE               1407 non-null   float64
 25  DATABASE_ID             1407 non-null   str
 26  DATABASE_ID_LABEL       1407 non-null   str
 27  UNIT_MULT               1407 non-null   int64
 28  UNIT_MULT_LABEL         1407 non-null   str
 29  UNIT_TYPE               1407 non-null   str
 30  UNIT_TYPE_LABEL         1407 non-null   str
 31  TIME_FORMAT             1407 non-null   int64
 32  TIME_FORMAT_LABEL       1407 non-null   str
 33  OBS_STATUS              1407 non-null   str
 34  OBS_STATUS_LABEL        1407 non-null   str
 35  OBS_CONF                1407 non-null   str
 36  OBS_CONF_LABEL          1407 non-null   str
dtypes: float64(1), int64(3), str(33)
memory usage: 406.8 KB
None

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public

# 2.2 LECTURA DE DATA CONTROLADA

In [3]:

import pandas as pd

# Archivo descargado desde World Bank Data360
RUTA_WORLD_BANK = "../data/WB_CLEAR_AQUASTAT_4554.csv"

df_world_bank = pd.read_csv(
    RUTA_WORLD_BANK,
    sep=",",
    encoding="utf-8",
    decimal=".",
    na_values=["", "NA", "N/A", "-", "null", "999"],
    skipinitialspace=True,
)

print(f"Filas: {df_world_bank.shape[0]}")
print(f"Columnas: {df_world_bank.shape[1]}")
df_world_bank.head()

Filas: 1407
Columnas: 37

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,UNIT_MULT,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A,Annual,CAN,Canada,WB_CLEAR_AQUASTAT_4554,SDG 6.4.1. Services Water Use Efficiency (US$/m3),_T,...,0,Units,CUR,Currency,602,CCYY,A,Normal value,PU,Public

# 3.PARCEAR DATOS

# 3.1 NUMEROS

In [11]:
# Conversión de las columnas numéricas del dataset

df_world_bank["TIME_PERIOD"] = pd.to_numeric(
    df_world_bank["TIME_PERIOD"],
    errors="coerce",
)
df_world_bank["OBS_VALUE"] = pd.to_numeric(
    df_world_bank["OBS_VALUE"],
    errors="coerce",
)

print(df_world_bank[["TIME_PERIOD", "OBS_VALUE"]].dtypes)
df_world_bank[["REF_AREA_LABEL", "TIME_PERIOD", "OBS_VALUE"]].head()

TIME_PERIOD      int64
OBS_VALUE      float64
dtype: object

  REF_AREA_LABEL  TIME_PERIOD   OBS_VALUE
0         Canada         2016  223.515276
1         Canada         2015  215.389365
2         Canada         2014  207.003010
3         Canada         2013  201.827792
4         Canada         2011  189.353633

# NUMEROS PERDIDOS

In [16]:
perdidos_en_parseo = df_world_bank["OBS_VALUE"].isna().sum()
perdidos_en_parseo_ = df_world_bank["TIME_PERIOD"].isna().sum()


print(f"Valores perdidos en OBS_VALUE: {perdidos_en_parseo}")
print(f"Valores perdidos en TIME_PERIOD: {perdidos_en_parseo_}")

Valores perdidos en OBS_VALUE: 0
Valores perdidos en TIME_PERIOD: 0

# 3.2 TEXTO Y CATEGORIAS

In [18]:
# Normalización de todas las columnas de texto
columnas_texto = df_world_bank.select_dtypes(include=["str"]).columns

for columna in columnas_texto:
    df_world_bank[columna] = (
        df_world_bank[columna]
        .astype("string")
        .str.strip()
        .str.lower()
        .replace("nan", pd.NA)
    )

print(f"Columnas de texto normalizadas: {len(columnas_texto)}")
df_world_bank[columnas_texto].head()

Columnas de texto normalizadas: 33

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,SEX,...,DATABASE_ID,DATABASE_ID_LABEL,UNIT_MULT_LABEL,UNIT_TYPE,UNIT_TYPE_LABEL,TIME_FORMAT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL
0,datastructure,wb.data360:ds_data360(1.2),i,a,annual,can,canada,wb_clear_aquastat_4554,sdg 6.4.1. services water use efficiency (us$/m3),_t,...,wb_clear,climate and economic analyses for resilience i...,units,cur,currency,ccyy,a,normal value,pu,public
1,datastructure,wb.data360:ds_data360(1.2),i,a,annual,can,canada,wb_clear_aquastat_4554,sdg 6.4.1. services water use efficiency (us$/m3),_t,...,wb_clear,climate and economic analyses for resilience i...,units,cur,currency,ccyy,a,normal value,pu,public
2,datastructure,wb.data360:ds_data360(1.2),i,a,annual,can,canada,wb_clear_aquastat_4554,sdg 6.4.1. services water use efficiency (us$/m3),_t,...,wb_clear,climate and economic analyses for resilience i...,units,cur,currency,ccyy,a,normal value,pu,public
3,datastructure,wb.data360:ds_data360(1.2),i,a,annual,can,canada,wb_clear_aquastat_4554,sdg 6.4.1. services water use efficiency (us$/m3),_t,...,wb_clear,climate and economic analyses for resilience i...,units,cur,currency,ccyy,a,normal value,pu,public
4,datastructure,wb.data360:ds_data360(1.2),i,a,annual,can,canada,wb_clear_aquastat_4554,sdg 6.4.1. services water use efficiency (us$/m3),_t,...,wb_clear,climate and economic analyses for resilience i...,units,cur,currency,ccyy,a,normal value,pu,public

# PERDIDOS TEXTO Y CATEGORIAS

In [19]:
# Valores perdidos en todas las columnas de texto
perdidos_texto = df_world_bank[columnas_texto].isna().sum()

print("Valores perdidos por columna de texto:")
print(perdidos_texto)

Valores perdidos por columna de texto:
STRUCTURE                 0
STRUCTURE_ID              0
ACTION                    0
FREQ                      0
FREQ_LABEL                0
REF_AREA                  0
REF_AREA_LABEL            0
INDICATOR                 0
INDICATOR_LABEL           0
SEX                       0
SEX_LABEL                 0
AGE                       0
AGE_LABEL                 0
URBANISATION              0
URBANISATION_LABEL        0
UNIT_MEASURE              0
UNIT_MEASURE_LABEL        0
COMP_BREAKDOWN_1          0
COMP_BREAKDOWN_1_LABEL    0
COMP_BREAKDOWN_2          0
COMP_BREAKDOWN_2_LABEL    0
COMP_BREAKDOWN_3          0
COMP_BREAKDOWN_3_LABEL    0
DATABASE_ID               0
DATABASE_ID_LABEL         0
UNIT_MULT_LABEL           0
UNIT_TYPE                 0
UNIT_TYPE_LABEL           0
TIME_FORMAT_LABEL         0
OBS_STATUS                0
OBS_STATUS_LABEL          0
OBS_CONF                  0
OBS_CONF_LABEL            0
dtype: int64

# 4.   DEPURACION DE DATOS

# 4.1 AUDITORIA MINIMA

In [20]:
# Auditoría mínima del dataset World Bank Data360
reporte = pd.DataFrame({
    "dtype": df_world_bank.dtypes.astype(str),
    "n_faltantes": df_world_bank.isna().sum(),
    "pct_faltantes": df_world_bank.isna().mean() * 100,
    "n_unicos": df_world_bank.nunique(dropna=False),
})

print(reporte)
print("Filas duplicadas:", df_world_bank.duplicated().sum())

                          dtype  n_faltantes  pct_faltantes  n_unicos
STRUCTURE                string            0            0.0         1
STRUCTURE_ID             string            0            0.0         1
ACTION                   string            0            0.0         1
FREQ                     string            0            0.0         1
FREQ_LABEL               string            0            0.0         1
REF_AREA                 string            0            0.0       183
REF_AREA_LABEL           string            0            0.0       183
INDICATOR                string            0            0.0         1
INDICATOR_LABEL          string            0            0.0         1
SEX                      string            0            0.0         1
SEX_LABEL                string            0            0.0         1
AGE                      string            0            0.0         1
AGE_LABEL                string            0            0.0         1
URBANISATION             string            0            0.0         1
URBANISATION_LABEL       string            0            0.0         1
UNIT_MEASURE             string            0            0.0         1
UNIT_MEASURE_LABEL       string            0            0.0         1
COMP_BREAKDOWN_1         string            0            0.0         1
COMP_BREAKDOWN_1_LABEL   string            0            0.0         1
COMP_BREAKDOWN_2         string            0            0.0         1
COMP_BREAKDOWN_2_LABEL   string            0            0.0         1
COMP_BREAKDOWN_3         string            0            0.0         1
COMP_BREAKDOWN_3_LABEL   string            0            0.0         1
TIME_PERIOD               int64            0            0.0        45
OBS_VALUE               float64            0            0.0      1407
DATABASE_ID              string            0            0.0         1
DATABASE_ID_LABEL        string            0            0.0         1
UNIT_MULT                 int64            0            0.0         1
UNIT_MULT_LABEL          string            0            0.0         1
UNIT_TYPE                string            0            0.0         1
UNIT_TYPE_LABEL          string            0            0.0         1
TIME_FORMAT               int64            0            0.0         1
TIME_FORMAT_LABEL        string            0            0.0         1
OBS_STATUS               string            0            0.0         1
OBS_STATUS_LABEL         string            0            0.0         1
OBS_CONF                 string            0            0.0         1
OBS_CONF_LABEL           string            0            0.0         1
Filas duplicadas: 0

# Complementos Utiles

In [ ]:
df["ciudad"].value_counts(dropna=False)
df.describe()
df.loc[df["edad"] < 0]

# 4.2 Duplicados

In [2]:
# Eliminación de copias exactas del dataset World Bank
filas_antes = len(df_world_bank)
df_world_bank = df_world_bank.drop_duplicates(keep="first")
filas_despues = len(df_world_bank)

print(f"Filas antes de eliminar duplicados: {filas_antes}")
print(f"Duplicados eliminados: {filas_antes - filas_despues}")
print(f"Filas después de eliminar duplicados: {filas_despues}")

Filas antes de eliminar duplicados: 1407
Duplicados eliminados: 0
Filas después de eliminar duplicados: 1407

# 4.3 Valores imposibles vs atípicos

In [3]:
# Identificación de valores atípicos en OBS_VALUE mediante el rango intercuartílico
q1, q3 = df_world_bank["OBS_VALUE"].quantile([0.25, 0.75])
iqr = q3 - q1
limite_inferior = q1 - 1.5 * iqr
limite_superior = q3 + 1.5 * iqr

atipicos = df_world_bank[
    (df_world_bank["OBS_VALUE"] < limite_inferior)
    | (df_world_bank["OBS_VALUE"] > limite_superior)
]

print(f"Primer cuartil (Q1): {q1:.2f}")
print(f"Tercer cuartil (Q3): {q3:.2f}")
print(f"IQR: {iqr:.2f}")
print(f"Límite inferior: {limite_inferior:.2f}")
print(f"Límite superior: {limite_superior:.2f}")
print(f"Valores atípicos encontrados: {len(atipicos)}")

atipicos[["REF_AREA_LABEL", "TIME_PERIOD", "OBS_VALUE"]].head()

Primer cuartil (Q1): 23.48
Tercer cuartil (Q3): 120.67
IQR: 97.19
Límite inferior: -122.31
Límite superior: 266.46
Valores atípicos encontrados: 94

    REF_AREA_LABEL  TIME_PERIOD   OBS_VALUE
116    Gambia, The         1982  306.840699
273     Luxembourg         1992  347.969885
282         Monaco         1992  449.844005
323    Switzerland         1992  272.898834
411     Luxembourg         1997  510.789705

# 5.2 Cuando si se puede eliminar datos

In [4]:
# Filas sin ningún valor
df_world_bank = df_world_bank.dropna(how="all")

# Columna casi vacía: se documenta y se deja fuera del análisis
umbral = 0.40
columnas_utiles = df_world_bank.columns[df_world_bank.isna().mean() < umbral]
columnas_excluidas = df_world_bank.columns.difference(columnas_utiles)
df_world_bank = df_world_bank[columnas_utiles]

print(f"Columnas conservadas: {len(columnas_utiles)}")
print(f"Columnas excluidas: {len(columnas_excluidas)}")

Columnas conservadas: 37
Columnas excluidas: 0

# 6.1 Imputacion por media/mediana/moda

In [5]:
# Imputación de valores numéricos en OBS_VALUE
media = df_world_bank["OBS_VALUE"].mean()
df_world_bank["OBS_VALUE_media"] = df_world_bank["OBS_VALUE"].fillna(media)

mediana = df_world_bank["OBS_VALUE"].median()
df_world_bank["OBS_VALUE_mediana"] = df_world_bank["OBS_VALUE"].fillna(mediana)

# Imputación de valores categóricos en REF_AREA_LABEL
moda = df_world_bank["REF_AREA_LABEL"].mode(dropna=True)
df_world_bank["REF_AREA_LABEL_moda"] = df_world_bank["REF_AREA_LABEL"].fillna(
    moda.iloc[0] if not moda.empty else pd.NA
)

print(f"Media de OBS_VALUE: {media:.2f}")
print(f"Mediana de OBS_VALUE: {mediana:.2f}")
print(f"Moda de REF_AREA_LABEL: {moda.iloc[0] if not moda.empty else 'Sin moda'}")

Media de OBS_VALUE: 94.14
Mediana de OBS_VALUE: 50.90
Moda de REF_AREA_LABEL: Chile

# 6.3 Imputacion que respeta la distribucion

# A. Muestreo de la distribución empírica (hot-deck aleatorio)

In [6]:
import numpy as np

obs = df_world_bank["OBS_VALUE"].dropna()
n_faltan = df_world_bank["OBS_VALUE"].isna().sum()

rng = np.random.default_rng(42)

if n_faltan > 0 and not obs.empty:
    imputados = rng.choice(obs.to_numpy(), size=n_faltan, replace=True)
    df_world_bank.loc[df_world_bank["OBS_VALUE"].isna(), "OBS_VALUE"] = imputados

print(f"Valores imputados aleatoriamente: {n_faltan if not obs.empty else 0}")

Valores imputados aleatoriamente: 0

# B. Media (o predicción) más ruido

In [7]:
obs = df_world_bank["OBS_VALUE"].dropna()
mu, sigma = obs.mean(), obs.std()
n_faltan = df_world_bank["OBS_VALUE"].isna().sum()

if n_faltan > 0 and not obs.empty:
    valores_imputados = rng.normal(mu, sigma, size=n_faltan)
    df_world_bank.loc[df_world_bank["OBS_VALUE"].isna(), "OBS_VALUE"] = valores_imputados

print(f"Valores imputados con distribución normal: {n_faltan if not obs.empty else 0}")

Valores imputados con distribución normal: 0

# 6.4 Imputación agrupada

In [8]:
faltantes_antes = df_world_bank["OBS_VALUE"].isna().sum()

df_world_bank["OBS_VALUE"] = df_world_bank.groupby("REF_AREA_LABEL")["OBS_VALUE"].transform(
    lambda serie: serie.fillna(serie.median())
)

faltantes_despues = df_world_bank["OBS_VALUE"].isna().sum()
print(f"Valores faltantes antes: {faltantes_antes}")
print(f"Valores faltantes después: {faltantes_despues}")

Valores faltantes antes: 0
Valores faltantes después: 0